apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: saikumarnerella90/order-service:v1
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: order-config
            - secretRef:
                name: order-secret

