apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-logs
  namespace: dev
spec:
  template:
    spec:
      containers:
      - name: cleaner
        image: busybox
        command: ["sh", "-c", "echo cleaning..."]
      restartPolicy: Never
  backoffLimit: 2

