pipeline {
  agent any

  environment {
    IMAGE_NAME = "saikumarnerella90/order-service"
    IMAGE_TAG = "v1"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ./services/order-service"
        }
      }
    }

   stage('Push to DockerHub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          script {
            docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
              docker.image("${IMAGE_NAME}:${IMAGE_TAG}").push()
            }
          }
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh 'kubectl apply -f manifests/base/namespace.yaml'
        sh 'kubectl apply -f manifests/base/order-service/'
      }
    }
  }
}
